### ISSUE TITLE
Need verify

### ISSUE THREAD

**Issue by jakubfrasunek** [DevFlock/ukraine-news-bot#3]
https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting

Unfortunately your bot is on 100 servers and we are not able to add it

**Comment by FloncDev** [comment]
Currently in the process of verifying, just having some trouble with making the Terms of Service since never made one before.

**Comment by FloncDev** [comment]
Waiting for discord to respond to application, should be verified within a few days.
