### ISSUE TITLE
Add webhook support

### ISSUE THREAD

**Issue by AirplanegoBrr** [DevFlock/ukraine-news-bot#7]
Make it so you can use webhook URLs
/webhook or something then the bot would kick its self or something.
Maybe make a website to enter webhook URLs and it will add it

**Comment by AirplanegoBrr** [comment]
I cant add Labels

**Comment by FloncDev** [comment]
This kinda defeats the purpose of the bot then

**Comment by AirplanegoBrr** [comment]
stupid idea
